# 
# SimpleSpawn
# by ellbristow
# 
# Configuration File
# 
# use_teleport_effect : Should a teleport effect be played on use of /spawn or /home?
# Allowed: true|false
# 
# teleport_effect_type : Which effect should be played on teleport?
# Allowed: 0 = Lightning, 1 = Ender Signal (default), 2 = Smoke, 3 = Flames

use_teleport_effect: true
teleport_effect_type: 1
set_home_with_beds: false
allow_spawn_in_jail: false